const products = [
  {
    id: 1,
    name: "极品凳子1",
    price: 200,
    image: "../../images/1.png",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 2,
    name: "极品凳子2",
    price: 250,
    image: "../../images/2.png",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 3,
    name: "极品凳子3",
    price: 290,
    image: "../../images/3.png",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 4,
    name: "极品凳子4",
    price: 200,
    image: "../../images/4.png",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 5,
    name: "极品凳子5",
    price: 300,
    image: "../../images/5.png",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 6,
    name: "极品凳子6",
    price: 200,
    image: "../../images/6.png",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 7,
    name: "极品凳子7",
    price: 200,
    image: "../../images/7.png",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 8,
    name: "极品凳子8",
    price: 200,
    image: "../../images/8.png",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 9,
    name: "美味甜椒",
    price: 700,
    image: "../../image/蔬菜/bell-peppers-499068.jpg",
    description: "产自江门五邑大学,采用了最新工艺",
  },
  {
    id: 10,
    name: "美味菜花",
    price: 700,
    image: "../../image/蔬菜/vegetables-1238252.jpg",
    description: "产自江门五邑大学，风味独特，十分可口！",
  },
  {
    id: 11,
    name: "美味绿豆",
    price: 700,
    image: "../../image/蔬菜/green-beans-1018624.jpg",
    description: "产自江门五邑大学，风味独特，十分可口！",
  },
  {
    id: 12,
    name: "美味胡萝卜",
    price: 700,
    image: "../../image/蔬菜/carrots-1508847.jpg",
    description: "产自江门五邑大学，风味独特，十分可口！",
  },
  {
    id: 13,
    name: "美味西瓜",
    price: 200,
    image: "../../image/水果/watermelon-833202.jpg",
    description: "产自江门五邑大学，风味独特，十分可口！",
  },
  {
    id: 14,
    name: "美味葡萄",
    price: 230,
    image: "../../image/水果/paris-2406492_1920.jpg",
    description: "产自江门五邑大学，风味独特，十分可口！",
  },
  {
    id: 15,
    name: "美味苹果",
    price: 230,
    image: "../../image/水果/apple-1122537_1920.jpg",
    description: "产自江门五邑大学，风味独特，十分可口！",
  },
  {
    id: 16,
    name: "蔬菜杂烩",
    price: 230,
    image: "../../image/蔬菜/vegetables-1238252.jpg",
    description: "产自江门五邑大学，风味独特，十分可口！",
  },
];
export default products;
